services:
  mongodb:
    image: mongo:8.0.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network

  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus configuration
    depends_on:
      - consul
    networks:
      - my-network

networks:
  my-network:
