services:
  mongodb:
    image: mongo:8.0.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network

  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500"
    networks:
      - my-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=no
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENER_NAMES=INSIDE,OUTSIDE
      - KAFKA_LISTENER_PORTS=9093,9094
      - KAFKA_LISTENER_NAME_INSIDE_PORT=9093
      - KAFKA_LISTENER_NAME_OUTSIDE_PORT=9094
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_NAME_OUTSIDE_HOST=localhost
      - KAFKA_ADVERTISED_LISTENER_OUTSIDE=localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    depends_on:
      - zookeeper
    volumes:
      - /var/lib/kafka/data
    networks:
      - my-network

networks:
  my-network:
