services:
  mongodb:
    image: mongo:8.0.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network

  consul:
    image: hashicorp/consul:latest
    container_name: consul-container
    ports:
      - "8500:8500"
    networks:
      - my-network

  fabio:
    image: fabiolb/fabio:latest
    container_name: fabio-container
    ports:
      - "9999:9999"
      - "9998:9998"  # Fabio Admin UI
    volumes:
      - ./fabio.properties:/etc/fabio/fabio.properties
    command: [ "-cfg", "/etc/fabio/fabio.properties" ]
    depends_on:
      - consul
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus configuration
    depends_on:
      - consul
    networks:
      - my-network

networks:
  my-network:
