global:
  scrape_interval: 15s  # Prometheus scrapes every 15 seconds

scrape_configs:
  - job_name: 'demo-app'
    consul_sd_configs:
      - server: 'consul:8500'  # Consul server address
        services: ['demo']  # Service name registered in Consul
    metrics_path: '/actuator/prometheus'  # Correct metrics path
    relabel_configs:
      # Combine service address and port correctly
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
        separator: ':'  # Use colon to separate address and port
        target_label: __address__
        replacement: '${1}${2}'  # Ensures format is IP:PORT

      # Optionally set an instance label for clarity
      - target_label: instance
        replacement: 'demo-app'


