spring:
  main:
    banner-mode: "OFF"
  data:
    mongodb:
      database: "demo"

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true

integration:
  radio-browser-api-url: "de1.api.radio-browser.info"