spring:
  main:
    banner-mode: "LOG"
  data:
    mongodb:
      database: "demo"
      host: localhost
      port: 27017

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true

integration:
  radio-browser-api-url: "http://de1.api.radio-browser.info:80"