spring:
  main:
    banner-mode: "OFF"
  data:
    mongodb:
      database: "demo"

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

integration:
  radio-browser-api-url: "de1.api.radio-browser.info:443"