server:
  port: 0
spring:
  application:
    name: @project.name@
    version: @project.version@
  main:
    banner-mode: "LOG"
  data:
    mongodb:
      database: "demo"
      host: localhost
      port: 27017
  config:
    import: "optional:consul:localhost:8500"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-group: demo
        instance-id: ${spring.application.name}:${spring.application.version}:${random.int}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
      config:
        enabled: true
    loadbalancer:
      cache:
        enabled: false

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true

integration:
  radio-browser-api-url: "https://de1.api.radio-browser.info:443"

resilience4j:
  retry:
    instances:
      radio-browser-retry:
        maxAttempts: 3
        waitDuration: 2000ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
  ratelimiter:
    instances:
      radio-browser-rate-limiter:
        limit-for-period: 1
        limit-refresh-period: 5s
        timeout-duration: 0